version: '2'
services:
  users-service:
    build: ./users-service
    ports:
     - "8123:8123"
     - "8080:8080"
    volumes:
      - ./users-service:/app
      - /app/node_modules
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./test-database
